backend:
  name: git-gateway
  branch: master

media_folder: 'static/img'
public_folder: '/img'

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short Title", name: "shortTitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Short Description", name: "shortDescription", widget: "text"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Role", name: "role", widget: "list"}
      - {label: "Technology", name: "technology", widget: "list", default: ["React", "HTML", "CSS", "JSX"]}
      - {label: "Card Image", name: "cardImage", widget: "image"}
      - {label: "Card Background Color", name: "cardBackground", widget: "string"}
      - {label: "Card Text Color", name: "cardText", widget: "select", default: "dark", options: ["dark", "light"] }
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "src/pages/about/index.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "text"}
          - {label: "Location", name: "location", widget: "string"}
          - {label: "Working At", name: "working", widget: "string"}
          - {label: "Countries Visited", name: "countries", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Subscriptions"
        name: "subscriptions"
        file: "src/pages/subscriptions/index.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "subscriptions-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Why Subscriptions Title", name: "whyTitle", widget: "string"}
          - {label: "Why Subscriptions Intro", name: "whyIntro", widget: "text"}
          - {label: "Why Subscriptions Details", name: "why1", widget: "text"}
          - {label: "Why Subscriptions Photo", name: "why1Photo", widget: "image"}
          - {label: "Why Subscriptions Details", name: "why2", widget: "text"}
          - {label: "Why Subscriptions Photo", name: "why2Photo", widget: "image"}
          - label: "Customer Care"
            name: "customerCare"
            widget: "object"
            fields:
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Team Name", name: "team", widget: "string"}
              - {label: "Team Description", name: "description", widget: "text"}
          - label: "Marketing Team"
            name: "marketing"
            widget: "object"
            fields:
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Team Name", name: "team", widget: "string"}
              - {label: "Team Description", name: "description", widget: "text"}
          - label: "Merchandising Team"
            name: "merchandising"
            widget: "object"
            fields:
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Team Name", name: "team", widget: "string"}
              - {label: "Team Description", name: "description", widget: "text"}
          - label: "Operations Team"
            name: "operations"
            widget: "object"
            fields:
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Team Name", name: "team", widget: "string"}
              - {label: "Team Description", name: "description", widget: "text"}
          - label: "Business Intelligence Team"
            name: "business"
            widget: "object"
            fields:
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Team Name", name: "team", widget: "string"}
              - {label: "Team Description", name: "description", widget: "text"}
          - label: "Engineering Team"
            name: "engineering"
            widget: "object"
            fields:
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Team Name", name: "team", widget: "string"}
              - {label: "Team Description", name: "description", widget: "text"}
