backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short Title", name: "short-title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Short Description", name: "short-description", widget: "text"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Role", name: "role", widget: "list"}
      - {label: "Technology", name: "technology", widget: "list", default: ["React", "HTML", "CSS", "JSX"]}
      - {label: "Card Image", name: "card-image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}