backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short Title", name: "shortTitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Short Description", name: "shortDescription", widget: "text"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Role", name: "role", widget: "list"}
      - {label: "Technology", name: "technology", widget: "list", default: ["React", "HTML", "CSS", "JSX"]}
      - {label: "Card Image", name: "cardImage", widget: "image"}
      - {label: "Card Background Color", name: "cardBackground", widget: "string"}
      - {label: "Card Text Color", name: "cardText", widget: "select", default: "dark", options: ["dark", "light"] }
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "src/pages/about/index.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "text"}
          - {label: "Location", name: "location", widget: "string"}
          - {label: "Working At", name: "working", widget: "string"}
          - {label: "Countries Visited", name: "countries", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
